- name : variables
  hosts: localhosts
  vars: 
    course: "ansible" 
    trainer : "siva kumar"
    duration : "120hrs" 
  tasks:
   - name : print the information
     ansible.bulitin.debug:
        msg: " hi , we are learning ansible from trainer sivakumar , duration 120 hrs"

