- name : variables
  hosts: localhost
  vars: 
    course: "python" 
    trainer : "rakesh"
    duration : "150hrs" 
  tasks:
   - name : print the information
     ansible.builtin.debug:
        msg: " hi , we are learning ansible from trainer sivakumar , duration 120 hrs"

