- name : variables
  hosts: localhost
  vars_file:
   vars.yaml
  tasks:
   - name : print the  override information
     ansible.builtin.debug:
       msg: " hi , we are learning {{course}} from trainer {{trainer}} , duration {{duration}}."


   