- name : variables from files
  hosts: localhost
  vars_prompt:
  tasks:
   tasks:
   - name : print the information
     ansible.builtin.debug:
        msg: " hi , we are learning {{course}} from trainer {{trainer}} , duration {{duration}}."
