 - name: conditions
   hosts: web 
   become: yes
   tasks: 
    - name: check user exists 
      ansible.builtin.command: id Experience
      ignore_errors : true


    - name : say "hello
      ansible.builtin.debug:
       msg: "hello"   